import { BridgeAgentTaskCreationError, enableBridgeAgentTaskCreation, readBridgeAgentTaskCreationStatus } from "./bridge-agent-task-creation.ts";
import { readEnableAgentAttachmentsBody } from "./exact-json-body.ts";
import { createGatewayAuthority, PROCESS_GATEWAY_AUTHORITY, type GatewayAuthority } from "./gateway-authority.ts";
import { GATEWAY_ROUTE_MANIFEST, type GatewayRouteRule } from "./gateway-route-manifest.ts";
import { withGatewayRoute } from "./gateway-request-context.ts";
const HEADERS = { "Cache-Control": "private, no-store", "Content-Security-Policy": "default-src 'none'; frame-ancestors 'none'", "Referrer-Policy": "no-referrer", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY" };
const fixed = (status: string, code: number) => Response.json({ schema_version: 1, status }, { headers: HEADERS, status: code });
function failure(error: unknown) { const code = error instanceof BridgeAgentTaskCreationError ? error.code : "error"; const map: Record<string, [string, number]> = { unavailable: ["unavailable", 503], conflict: ["conflict", 409], invalid: ["invalid", 400], not_found: ["not_found", 404], unsupported: ["unsupported", 415] }; const result = map[code]; return result ? fixed(result[0], result[1]) : fixed("error", 502); }
function route(method: GatewayRouteRule["method"], path: GatewayRouteRule["path"]): GatewayRouteRule { const found = GATEWAY_ROUTE_MANIFEST.find((candidate) => candidate.method === method && candidate.path === path); if (!found) throw new Error(`missing gateway manifest rule for ${method} ${path}`); return found; }
const ENABLE_PATH = "/api/agents/[agentId]/task-creation/enable" as const;
const POST_RULE = route("POST", ENABLE_PATH);
const GET_RULE = route("GET", ENABLE_PATH);
function authorityFor(gatewayPort: string | undefined): Pick<GatewayAuthority, "authorize"> { return gatewayPort === process.env.PORT ? PROCESS_GATEWAY_AUTHORITY : createGatewayAuthority({ PORT: gatewayPort }); }
type AgentContext = { params: Promise<{ agentId: string }> };
type EnableValue = { agentId: string; body: { expectedCapabilities: string[] } } | null;
export function createEnableAgentTaskCreationHandler({ gatewayPort = process.env.PORT, enable = enableBridgeAgentTaskCreation } = {}) { return withGatewayRoute<EnableValue, AgentContext>(POST_RULE, { authority: authorityFor(gatewayPort), handler: async ({ value }) => { if (!value) return fixed("invalid", 400); try { return Response.json(await enable(value.agentId, value.body.expectedCapabilities), { headers: HEADERS, status: 200 }); } catch (error) { return failure(error); } }, validator: { async validate(request, _context, context) { if (new URL(request.url).search) return null; const body = await readEnableAgentAttachmentsBody(request); return body ? { agentId: (await context.params).agentId, body } : null; } } }); }
export function createAgentTaskCreationStatusHandler({ gatewayPort = process.env.PORT, read = readBridgeAgentTaskCreationStatus } = {}) { return withGatewayRoute<string | null, AgentContext>(GET_RULE, { authority: authorityFor(gatewayPort), handler: async ({ value }) => { if (!value) return fixed("invalid", 400); try { return Response.json({ schema_version: 1, service: "mentat-local-bridge", runtime: "python", status: "ready", agent_id: value, state: await read(value) }, { headers: HEADERS, status: 200 }); } catch (error) { return failure(error); } }, validator: { async validate(request, _context, context) { return new URL(request.url).search ? null : (await context.params).agentId; } } }); }
