import { BridgeAgentTaskCreationError, enableBridgeAgentTaskCreation, readBridgeAgentTaskCreationStatus } from "./bridge-agent-task-creation.ts";
import { readEnableAgentAttachmentsBody } from "./exact-json-body.ts";
import { evaluateRequestBoundary, parseGatewayPort } from "./request-boundary.ts";
const HEADERS = { "Cache-Control": "private, no-store", "Content-Security-Policy": "default-src 'none'; frame-ancestors 'none'", "Referrer-Policy": "no-referrer", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY" };
const fixed = (status: string, code: number) => Response.json({ schema_version: 1, status }, { headers: HEADERS, status: code });
function failure(error: unknown) { const code = error instanceof BridgeAgentTaskCreationError ? error.code : "error"; const map: Record<string, [string, number]> = { unavailable: ["unavailable", 503], conflict: ["conflict", 409], invalid: ["invalid", 400], not_found: ["not_found", 404], unsupported: ["unsupported", 415] }; const result = map[code]; return result ? fixed(result[0], result[1]) : fixed("error", 502); }
function allowed(request: Request, method: string, port: string | undefined) { return evaluateRequestBoundary({ expectedPort: parseGatewayPort(port), host: request.headers.get("host"), method, origin: request.headers.get("origin"), secFetchSite: request.headers.get("sec-fetch-site") }).allowed && !new URL(request.url).search; }
export function createEnableAgentTaskCreationHandler({ gatewayPort = process.env.PORT, enable = enableBridgeAgentTaskCreation } = {}) { return async (request: Request, context: { params: Promise<{ agentId: string }> }) => { if (!allowed(request, "POST", gatewayPort)) return new Response("Forbidden\n", { headers: HEADERS, status: 403 }); const body = await readEnableAgentAttachmentsBody(request); if (!body) return fixed("invalid", 400); const { agentId } = await context.params; try { return Response.json(await enable(agentId, body.expectedCapabilities), { headers: HEADERS, status: 200 }); } catch (error) { return failure(error); } }; }
export function createAgentTaskCreationStatusHandler({ gatewayPort = process.env.PORT, read = readBridgeAgentTaskCreationStatus } = {}) { return async (request: Request, context: { params: Promise<{ agentId: string }> }) => { if (!allowed(request, "GET", gatewayPort)) return new Response("Forbidden\n", { headers: HEADERS, status: 403 }); const { agentId } = await context.params; try { return Response.json({ schema_version: 1, service: "mentat-local-bridge", runtime: "python", status: "ready", agent_id: agentId, state: await read(agentId) }, { headers: HEADERS, status: 200 }); } catch (error) { return failure(error); } }; }
