import { validRunId } from "./bridge-run-events.ts";

const PATH = "/bridge/v1/runs/";
const MAX_BYTES = 4_096;
const RUN_MESSAGE_TEXT_LIMIT = 6_000;
const withinRunMessageTextLimit = (text: string) => Array.from(text).length <= RUN_MESSAGE_TEXT_LIMIT;
type Environment = Readonly<Record<string, string | undefined>>;
type FetchLike = (input: string | URL | Request, init?: RequestInit) => Promise<Response>;
export class BridgeRunMessageError extends Error { readonly code: string; constructor(code: string) { super(code); this.code = code; } }
type Preview = { schema_version: 1; service: "mentat-local-bridge"; runtime: "python"; status: "ready"; action: "message"; run_id: string; requires_confirmation: true; confirmation_id: string };
type Result = { schema_version: 1; service: "mentat-local-bridge"; runtime: "python"; status: "ready"; action: "message"; run_id: string; disposition: "accepted" };
function configuration(environment: Environment) { const token = environment.MENTAT_BRIDGE_TOKEN ?? ""; let url: URL; try { url = new URL(environment.MENTAT_BRIDGE_ORIGIN ?? ""); } catch { throw new BridgeRunMessageError("bridge_configuration_invalid"); } const host = url.hostname.toLowerCase().replace(/^\[|\]$/gu, ""); if (url.protocol !== "http:" || !new Set(["127.0.0.1", "::1"]).has(host) || !url.port || url.username || url.password || url.pathname !== "/" || url.search || url.hash || !/^[A-Za-z0-9_-]{43,256}$/u.test(token)) throw new BridgeRunMessageError("bridge_configuration_invalid"); return { origin: url.origin, token }; }
async function bounded(response: Response): Promise<unknown> { const length = response.headers.get("content-length"); if (length && (!/^\d{1,10}$/u.test(length) || Number(length) > MAX_BYTES)) throw new BridgeRunMessageError("bridge_response_invalid"); const text = await response.text(); if (new TextEncoder().encode(text).byteLength > MAX_BYTES) throw new BridgeRunMessageError("bridge_response_invalid"); try { return JSON.parse(text); } catch { throw new BridgeRunMessageError("bridge_response_invalid"); } }
function failure(response: Response, payload: unknown): never { const fixed = (state: string) => !!payload && typeof payload === "object" && !Array.isArray(payload) && Object.keys(payload as object).sort().join(",") === "runtime,schema_version,service,status" && (payload as Record<string, unknown>).schema_version === 1 && (payload as Record<string, unknown>).service === "mentat-local-bridge" && (payload as Record<string, unknown>).runtime === "python" && (payload as Record<string, unknown>).status === state; if (response.status === 404 && fixed("not_found")) throw new BridgeRunMessageError("run_not_found"); if (response.status === 409 && fixed("conflict")) throw new BridgeRunMessageError("action_conflict"); if (response.status === 501 && fixed("unsupported")) throw new BridgeRunMessageError("action_unsupported"); if (response.status === 503 && fixed("unavailable")) throw new BridgeRunMessageError("bridge_unavailable"); if (response.status === 400 && fixed("invalid")) throw new BridgeRunMessageError("request_invalid"); if (response.status === 500 && fixed("error")) throw new BridgeRunMessageError("action_failed"); throw new BridgeRunMessageError("bridge_response_invalid"); }
async function request(runId: string, suffix: string, body: object, fetcher: FetchLike, environment: Environment) { if (!validRunId(runId)) throw new BridgeRunMessageError("request_invalid"); const bridge = configuration(environment); let response: Response; try { response = await fetcher(new URL(`${PATH}${encodeURIComponent(runId)}/message${suffix}`, bridge.origin), { method: "POST", cache: "no-store", redirect: "error", headers: { Accept: "application/json", "Content-Type": "application/json", "X-Mentat-Bridge-Token": bridge.token }, body: JSON.stringify(body), signal: AbortSignal.timeout(1_500) }); } catch { throw new BridgeRunMessageError("bridge_unavailable"); } if (!response.headers.get("content-type")?.toLowerCase().startsWith("application/json")) throw new BridgeRunMessageError("bridge_response_invalid"); return { response, payload: await bounded(response) }; }
export async function previewBridgeRunMessage(runId: string, text: string, fetcher: FetchLike = fetch, environment: Environment = process.env): Promise<Preview> { if (typeof text !== "string" || !text.trim() || !withinRunMessageTextLimit(text) || text.includes("\0")) throw new BridgeRunMessageError("request_invalid"); const { response, payload } = await request(runId, "/preview", { text }, fetcher, environment); if (response.status === 200 && payload && typeof payload === "object" && !Array.isArray(payload)) { const item = payload as Record<string, unknown>; if (Object.keys(item).sort().join(",") === "action,confirmation_id,requires_confirmation,run_id,runtime,schema_version,service,status" && item.schema_version === 1 && item.service === "mentat-local-bridge" && item.runtime === "python" && item.status === "ready" && item.action === "message" && item.run_id === runId && item.requires_confirmation === true && typeof item.confirmation_id === "string" && /^[0-9a-f]{64}$/u.test(item.confirmation_id)) return item as Preview; } return failure(response, payload); }
export async function confirmBridgeRunMessage(runId: string, text: string, confirmationId: string, fetcher: FetchLike = fetch, environment: Environment = process.env): Promise<Result> { if (typeof text !== "string" || !text.trim() || !withinRunMessageTextLimit(text) || text.includes("\0") || !/^[0-9a-f]{64}$/u.test(confirmationId)) throw new BridgeRunMessageError("request_invalid"); const { response, payload } = await request(runId, "", { text, confirmation_id: confirmationId }, fetcher, environment); if (response.status === 202 && payload && typeof payload === "object" && !Array.isArray(payload)) { const item = payload as Record<string, unknown>; if (Object.keys(item).sort().join(",") === "action,disposition,run_id,runtime,schema_version,service,status" && item.schema_version === 1 && item.service === "mentat-local-bridge" && item.runtime === "python" && item.status === "ready" && item.action === "message" && item.run_id === runId && item.disposition === "accepted") return item as Result; } return failure(response, payload); }
