import {
  confirmBridgePlanningTaskDelegation,
  confirmBridgePlanningTaskDelegationAction,
  fetchBridgePlanningTaskDelegationOptions,
  previewBridgePlanningTaskDelegation,
  previewBridgePlanningTaskDelegationAction,
  recoverBridgePlanningTaskDelegation,
  refreshBridgePlanningTaskDelegation,
} from "./bridge-planning.ts";
import { PLANNING_HEADERS, planningFailure, planningFixed, planningRequestAllowed } from "./planning-overview-route.ts";
import type { DelegationAction, PublicPlanningTaskDelegationMutation, PublicPlanningTaskDelegationOptions, PublicPlanningTaskDelegationPreview, PublicPlanningTaskDelegationRecovery, PublicPlanningTaskDelegationRefresh } from "./public-planning-task-delegation-actions.ts";

type Params = { params: Promise<{ taskId: string }> };
const TASK = /^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,159}$/u;
const TARGET = /^[A-Za-z0-9][A-Za-z0-9_-]*$/u;
const DELEGATE_CONFIRMATION = /^task_delegate_[0-9a-f]{24}$/u;
const ACTION_CONFIRMATION = /^delegation_action_[0-9a-f]{24}$/u;
const NOTE_ACTIONS = new Set<DelegationAction>(["reply", "request_revision", "mark_blocked"]);
const ACTIONS = new Set<DelegationAction>(["accept", "reply", "retry", "stop", "request_revision", "mark_blocked"]);

function exact(value: Record<string, unknown>, fields: readonly string[]) { return Object.keys(value).sort().join(",") === [...fields].sort().join(","); }
function positive(value: unknown): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 1; }
function target(value: unknown, maximum: number): value is string { return typeof value === "string" && value.length <= maximum && TARGET.test(value); }
function input(value: unknown, maximum: number): value is string { return typeof value === "string" && [...value].length <= maximum && !/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/u.test(value); }
function idempotency(value: unknown): value is string { if (typeof value !== "string" || value.includes("\x00")) return false; try { const bytes = new TextEncoder().encode(value); return bytes.length >= 16 && bytes.length <= 256 && new TextDecoder("utf-8", { fatal: true }).decode(bytes) === value; } catch { return false; } }
async function taskId(context: Params) { const { taskId: value } = await context.params; return TASK.test(value) ? value : null; }
async function body(request: Request): Promise<Record<string, unknown> | null> { if (request.headers.get("content-type")?.toLowerCase() !== "application/json" || !request.body) return null; const declared = request.headers.get("content-length"); if (declared && (!/^\d{1,6}$/u.test(declared) || Number(declared) > 16_384)) return null; const reader = request.body.getReader(); const chunks: Uint8Array[] = []; let size = 0; try { for (;;) { const part = await reader.read(); if (part.done) break; size += part.value.byteLength; if (size > 16_384) { await reader.cancel(); return null; } chunks.push(part.value); } } catch { await reader.cancel().catch(() => undefined); return null; } finally { reader.releaseLock(); } const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } try { const value: unknown = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes)); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function delegate(value: Record<string, unknown>, confirmation: boolean): value is { expected_revision: number; profile_id: string; board_id: string; workspace: "scratch" | "worktree"; instructions: string; context_pack_id: string; confirmation_id: string; idempotency_key: string } { const fields = ["expected_revision", "profile_id", "board_id", "workspace", "instructions", "context_pack_id", ...(confirmation ? ["confirmation_id", "idempotency_key"] : [])]; return exact(value, fields) && positive(value.expected_revision) && target(value.profile_id, 80) && target(value.board_id, 64) && (value.workspace === "scratch" || value.workspace === "worktree") && input(value.instructions, 8_000) && (value.context_pack_id === "" || typeof value.context_pack_id === "string" && /^pack_[0-9a-f]{16}$/u.test(value.context_pack_id)) && (!confirmation || typeof value.confirmation_id === "string" && DELEGATE_CONFIRMATION.test(value.confirmation_id) && idempotency(value.idempotency_key)); }
function action(value: Record<string, unknown>, confirmation: boolean): value is { expected_revision: number; action: Exclude<DelegationAction, "delegate">; note?: string; confirmation_id: string; idempotency_key: string } { if (!positive(value.expected_revision) || typeof value.action !== "string" || !ACTIONS.has(value.action as DelegationAction)) return false; const selected = value.action as Exclude<DelegationAction, "delegate">; const fields = ["expected_revision", "action", ...(NOTE_ACTIONS.has(selected) ? ["note"] : []), ...(confirmation ? ["confirmation_id", "idempotency_key"] : [])]; return exact(value, fields) && (!NOTE_ACTIONS.has(selected) || input(value.note, 8_000) && !!value.note.trim()) && (!confirmation || typeof value.confirmation_id === "string" && ACTION_CONFIRMATION.test(value.confirmation_id) && idempotency(value.idempotency_key)); }
function allowed(request: Request, gatewayPort: string | undefined) { return planningRequestAllowed(request, gatewayPort); }

export function createPlanningTaskDelegationOptionsHandler({ readOptions = fetchBridgePlanningTaskDelegationOptions, gatewayPort = process.env.PORT }: Readonly<{ readOptions?: (taskId: string) => Promise<PublicPlanningTaskDelegationOptions>; gatewayPort?: string }> = {}) { return async (request: Request) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); const entries = [...new URL(request.url).searchParams.entries()]; if (entries.length !== 1 || entries[0]![0] !== "task_id" || !TASK.test(entries[0]![1])) return planningFixed("invalid", 400); try { return Response.json(await readOptions(entries[0]![1]), { headers: PLANNING_HEADERS }); } catch (error) { return planningFailure(error); } }; }
export function createPlanningTaskDelegationPreviewHandler({ preview = previewBridgePlanningTaskDelegation, gatewayPort = process.env.PORT }: Readonly<{ preview?: (taskId: string, expectedRevision: number, profileId: string, boardId: string, workspace: "scratch" | "worktree", instructions: string, contextPackId: string) => Promise<PublicPlanningTaskDelegationPreview>; gatewayPort?: string }> = {}) { return async (request: Request, context: Params) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); if (new URL(request.url).search) return planningFixed("invalid", 400); const id = await taskId(context); const value = await body(request); if (!id || !value || !delegate(value, false)) return planningFixed("invalid", 400); try { return Response.json(await preview(id, value.expected_revision, value.profile_id, value.board_id, value.workspace, value.instructions, value.context_pack_id), { headers: PLANNING_HEADERS }); } catch (error) { return planningFailure(error); } }; }
export function createPlanningTaskDelegateHandler({ confirm = confirmBridgePlanningTaskDelegation, gatewayPort = process.env.PORT }: Readonly<{ confirm?: (taskId: string, expectedRevision: number, profileId: string, boardId: string, workspace: "scratch" | "worktree", instructions: string, contextPackId: string, confirmationId: string, idempotencyKey: string) => Promise<PublicPlanningTaskDelegationMutation>; gatewayPort?: string }> = {}) { return async (request: Request, context: Params) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); if (new URL(request.url).search) return planningFixed("invalid", 400); const id = await taskId(context); const value = await body(request); if (!id || !value || !delegate(value, true)) return planningFixed("invalid", 400); try { return Response.json(await confirm(id, value.expected_revision, value.profile_id, value.board_id, value.workspace, value.instructions, value.context_pack_id, value.confirmation_id, value.idempotency_key), { headers: PLANNING_HEADERS, status: 201 }); } catch (error) { return planningFailure(error); } }; }
export function createPlanningTaskDelegationActionPreviewHandler({ preview = previewBridgePlanningTaskDelegationAction, gatewayPort = process.env.PORT }: Readonly<{ preview?: (taskId: string, expectedRevision: number, action: Exclude<DelegationAction, "delegate">, note: string | null) => Promise<PublicPlanningTaskDelegationPreview>; gatewayPort?: string }> = {}) { return async (request: Request, context: Params) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); if (new URL(request.url).search) return planningFixed("invalid", 400); const id = await taskId(context); const value = await body(request); if (!id || !value || !action(value, false)) return planningFixed("invalid", 400); try { return Response.json(await preview(id, value.expected_revision, value.action, NOTE_ACTIONS.has(value.action) ? value.note! : null), { headers: PLANNING_HEADERS }); } catch (error) { return planningFailure(error); } }; }
export function createPlanningTaskDelegationActionHandler({ confirm = confirmBridgePlanningTaskDelegationAction, gatewayPort = process.env.PORT }: Readonly<{ confirm?: (taskId: string, expectedRevision: number, action: Exclude<DelegationAction, "delegate">, note: string | null, confirmationId: string, idempotencyKey: string) => Promise<PublicPlanningTaskDelegationMutation>; gatewayPort?: string }> = {}) { return async (request: Request, context: Params) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); if (new URL(request.url).search) return planningFixed("invalid", 400); const id = await taskId(context); const value = await body(request); if (!id || !value || !action(value, true)) return planningFixed("invalid", 400); try { return Response.json(await confirm(id, value.expected_revision, value.action, NOTE_ACTIONS.has(value.action) ? value.note! : null, value.confirmation_id, value.idempotency_key), { headers: PLANNING_HEADERS }); } catch (error) { return planningFailure(error); } }; }
export function createPlanningTaskDelegationRefreshHandler({ refresh = refreshBridgePlanningTaskDelegation, gatewayPort = process.env.PORT }: Readonly<{ refresh?: (taskId: string, expectedRevision: number) => Promise<PublicPlanningTaskDelegationRefresh>; gatewayPort?: string }> = {}) { return async (request: Request, context: Params) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); if (new URL(request.url).search) return planningFixed("invalid", 400); const id = await taskId(context); const value = await body(request); if (!id || !value || !exact(value, ["expected_revision"]) || !positive(value.expected_revision)) return planningFixed("invalid", 400); try { return Response.json(await refresh(id, value.expected_revision), { headers: PLANNING_HEADERS }); } catch (error) { return planningFailure(error); } }; }
export function createPlanningTaskDelegationRecoverHandler({ recover = recoverBridgePlanningTaskDelegation, gatewayPort = process.env.PORT }: Readonly<{ recover?: (taskId: string, confirmationId: string, idempotencyKey: string) => Promise<PublicPlanningTaskDelegationRecovery>; gatewayPort?: string }> = {}) { return async (request: Request, context: Params) => { if (!allowed(request, gatewayPort)) return new Response("Forbidden\n", { headers: PLANNING_HEADERS, status: 403 }); if (new URL(request.url).search) return planningFixed("invalid", 400); const id = await taskId(context); const value = await body(request); if (!id || !value || !exact(value, ["confirmation_id", "idempotency_key"]) || typeof value.confirmation_id !== "string" || !/^(?:task_delegate|delegation_action)_[0-9a-f]{24}$/u.test(value.confirmation_id) || !idempotency(value.idempotency_key)) return planningFixed("invalid", 400); try { return Response.json(await recover(id, value.confirmation_id, value.idempotency_key), { headers: PLANNING_HEADERS }); } catch (error) { return planningFailure(error); } }; }
